development:
  adapter: postgresql
  database: mythink_development
  min_messages: warning
  host: localhost
  pool: 5
  username: postgres
  password: postgres

staging:
  adapter: postgresql
  database: mythink_staging
  min_messages: warning
  host: localhost
  pool: 5
  username: postgres
  password: postgres

